name: Eleventy Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.3
        with:
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          cname: italocalvino.it
